services:
  - type: web
    name: flux-image-generator
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker render_server:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: HUGGINGFACE_TOKEN
        sync: false
